# for racetracks data
racetrack:
  workspace_path: "~/catkin_ws"
  0:
    cmd: "roslaunch nics_bringup nics_gazebo_simple.launch"
    max_seconds: 120
    track_width: 1.0
    init_pose: 
      x: 0.45
      y: -1.79
    half_pose: 
      x: -0.35
      y: 0
  1:
    cmd: "roslaunch nics_bringup nics_gazebo_block.launch"
    max_seconds: 120
    track_width: 1.0
    init_pose: 
      x: 0.45
      y: -1.79
    half_pose: 
      x: -0.35
      y: 0
  2:
    cmd: "roslaunch nics_bringup nics_gazebo_actor_new.launch"
    max_seconds: 300
    track_width: 1.1
    init_pose: 
      x: 4.4
      y: -2.6
    half_pose: 
      x: -4.0
      y: 0.75
    # *******************************极其朴素的赛道出圈检测方法**************************
    ############################################注意半径检测时，全部乘1.25
    # 障碍物1前  
    #(6.0+0.125/2,-2.5-0.125/2,sqrt(2)*3*0.125）
    # 6.0+0.125*3,-2.5+0.125*5,4*0.125
    # 障碍物1后 （6.0，-0.5）
    # 6.0+0.25,-0.5-0.5,0.125*4
    # 6.0,-0.5,sqrt(2)*3*0.125
    # 5.5+0.125,0,sqrt(2)*2.5*0.125
    # 5.0,0.5,sqrt(2)*3*0.125
    # 障碍物2之后
    # 4.0,1.0,sqrt(2)*3*0.125
    # 道路合并之后
    # -4.0,0.75,0.5
    # -5.0-0.25,0.5+0.25,0.5
    #-5.25,-0.5,0.5
    #-2.5,-0.5,0.5
    #-2.5,-1.5,0.5
    #-5.0,-1.5-0.25,0.5
    #-5.0,-2.5-0.25,0.5
    # 弯道
    # -3.0,-2.5-0.25,0.5
    # -1.5,-4.0,0.5
    # 0.5,-2.75,0.5
    # 2.75,-4.0,0.5
    # 4.0,-2.75,0.5

    check_pose_list: [[6.0625,-2.5625,0.53],
                      [6.375,-1.875,0.5],
                      [6.25,-1.0,0.5],
                      [6.0,-0.5,0.53],
                      [5.625,0,0.5],
                      [5.0,0.5,0.53],
                      [4.0,1.0,0.53],
                      # 道路合并之后
                      [-4.0,0.75,0.5],
                      [-5.25,0.75,0.5],
                      [-5.25,-0.5,0.5],
                      [-2.5,-0.5,0.5],
                      [-2.5,-1.5,0.5],
                      [-5.0,-1.75,0.5],
                      [-5.0,-2.75,0.5],
                      # 弯道
                      [-3.0,-2.75,0.5],
                      [-1.5,-4.0,0.5],
                      [0.5,-2.75,0.5],
                      [2.75,-4.0,0.5],
                      [4.0,-2.75,0.5]]
    #半圆
    select_R_pose_list: [[1.5,3.0,0.53],
                         [-1.0,4.0,0.5],
                         [-3.5625,2.5,0.5]]
    # 直线
    # 1.0,1.25,0.5
    select_L_pose_list: [[1.0,1.25,0.5],
                         [-1.0,1.25,0.5],
                         [-2.5,1.25,0.5] ]
    #*************************************************************************************

# for user test config
user_cmd: 
  0: "roslaunch nicsrobot_line_follower nicsrobot_line_follower.launch"
  1: "roslaunch nicsrobot_line_follower nicsrobot_line_follower_2.launch"
  2: "roslaunch nicsrobot_line_follower nicsrobot_line_follower_3.launch"
rebuild_workspace: true
unzip_workspace: true